export const BackgroundColor = "#e3e5e2"; /*paleTealLabenu*/
export const yellowLabenu = "#fbb44c";
export const SecondaryColor = "#fad69b"; /*lightYellowLabenu*/
export const orangeLabenu = "#F27D1E";
export const PrimaryColor = "#bd6413"; /*darkOrangeLabenu*/
export const brownLabenu = "#725D4B";
export const lightBrownLabenu = "#b4844c";
export const lightGrayLabenu = "#AAB8C6";
export const darkGrayLabenu = "#45525b";
export const mediumGrayLabenu = "#757c82";
export const lightTealLabenu = "#9cacac";